# Celestia Indexer Configuration
# This configuration file is used by celestia-indexer
# Connection details are provided via environment variables in docker-compose.yml

version: 1.0
spec_version: 2.0
package: celestia_indexer

database:
  kind: postgres
  host: postgres
  port: 5432
  user: celestia
  password: celestia
  database: celestia

datasources:
  node_rpc:
    kind: http
    url: http://celestia-app:26657
  node_api:
    kind: http
    url: http://celestia-app:1317

indexer:
  name: celestia
  block_period: 1

api:
  host: 0.0.0.0
  port: 9876
